version: "3.1"

services:

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379

    celery:
        container_name: celery
        build:
            context: "."
        command: celery -A task worker -Q analysis --concurrency=1 --loglevel=info -E
        volumes:
            - ./:/usr/src/app
        depends_on:
            - "redis"

    app:
        container_name: app
        build:
            context: "."
        command: python main.py
        volumes:
            - ./:/usr/src/app
        depends_on:
            - "redis"

